version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: conductor-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conductor
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: conductor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Opcional: Interface web para PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: conductor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conductor.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - tools

  # Opcional: Interface web para Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: conductor-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools

volumes:
  postgres-data:
  redis-data: